# Generated by Django 5.1.15 on 2026-09-18 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("education", "تحصیلات"),
                            ("experience", "سوابق شغلی"),
                            ("certificate", "گواهی\u200cنامه و افتخارات"),
                            ("membership", "عضویت\u200cها"),
                        ],
                        default="experience",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="عنوان")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="سازمان / دانشگاه"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="مثال: ۱۳۹۵ تا ۱۴۰۰",
                        max_length=60,
                        verbose_name="بازه زمانی",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "سابقه / افتخار",
                "verbose_name_plural": "سوابق و افتخارات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="پرسش")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شود"),
                ),
            ],
            options={
                "verbose_name": "پرسش متداول",
                "verbose_name_plural": "پرسش\u200cهای متداول",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="عنوان صفحه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=180,
                        unique=True,
                        verbose_name="نشانی اینترنتی",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا (HTML مجاز است)")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شود"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="نمایش در فوتر"),
                ),
            ],
            options={
                "verbose_name": "صفحه ثابت",
                "verbose_name_plural": "صفحات ثابت",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان خدمت")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=140,
                        unique=True,
                        verbose_name="نشانی اینترنتی",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="scale",
                        help_text="یکی از: scale, gavel, family, home, briefcase, contract, shield, bank, doc, check",
                        max_length=40,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(max_length=250, verbose_name="توضیح کوتاه"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="توضیح کامل (HTML مجاز است)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="practice/", verbose_name="تصویر"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه نخست"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "زمینه تخصصی / خدمت",
                "verbose_name_plural": "زمینه\u200cهای تخصصی و خدمات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان مرحله")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="check", max_length=40, verbose_name="آیکون"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "مرحله همکاری",
                "verbose_name_plural": "مراحل همکاری",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="دفتر وکالت", max_length=120, verbose_name="نام سایت"
                    ),
                ),
                (
                    "lawyer_name",
                    models.CharField(
                        default="نام وکیل",
                        max_length=120,
                        verbose_name="نام و نام خانوادگی وکیل",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        default="وکیل پایه یک دادگستری و مشاور حقوقی",
                        max_length=160,
                        verbose_name="عنوان شغلی",
                    ),
                ),
                (
                    "bar_association",
                    models.CharField(
                        blank=True,
                        default="کانون وکلای دادگستری مرکز",
                        max_length=120,
                        verbose_name="کانون وکلای دادگستری",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="شماره پروانه وکالت"
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="دفاع حرفه\u200cای از حقوق شما",
                        max_length=200,
                        verbose_name="تیتر اصلی صفحه نخست",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="مشاوره تخصصی و وکالت در پرونده\u200cهای حقوقی، کیفری، خانواده و ملکی.",
                        verbose_name="توضیح کوتاه صفحه نخست",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="تصویر صفحه نخست"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="عکس پرسنلی وکیل"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="site/", verbose_name="فاوآیکون"
                    ),
                ),
                (
                    "about_short",
                    models.TextField(blank=True, verbose_name="معرفی کوتاه"),
                ),
                (
                    "about_full",
                    models.TextField(
                        blank=True, verbose_name="معرفی کامل (HTML مجاز است)"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="تلفن تماس"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="تلفن دوم"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=30, verbose_name="موبایل"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="واتساپ (با کد کشور، مثال: 989121234567)",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="تلگرام (بدون @)"
                    ),
                ),
                (
                    "eitaa",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="ایتا (بدون @)"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="اینستاگرام (بدون @)"
                    ),
                ),
                (
                    "aparat_channel",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="نام کانال آپارات (بدون @)",
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="لینکدین")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس دفتر")),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="شنبه تا چهارشنبه، ۹ تا ۱۸",
                        max_length=160,
                        verbose_name="ساعات کاری",
                    ),
                ),
                (
                    "map_embed",
                    models.TextField(
                        blank=True,
                        help_text="کد iframe نقشه را اینجا قرار دهید.",
                        verbose_name="کد امبد نقشه (iframe نشان یا گوگل\u200cمپ)",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیحات متا (سئو)"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمات کلیدی (سئو)"
                    ),
                ),
                (
                    "enamad_code",
                    models.TextField(
                        blank=True, verbose_name="کد نماد اعتماد الکترونیکی"
                    ),
                ),
                (
                    "analytics_code",
                    models.TextField(blank=True, verbose_name="کد آنالیتیکس / آمارگیر"),
                ),
                (
                    "footer_note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="متن فوتر"
                    ),
                ),
                (
                    "consultation_note",
                    models.CharField(
                        blank=True,
                        default="درخواست شما در اسرع وقت بررسی و با شما تماس گرفته می\u200cشود.",
                        max_length=250,
                        verbose_name="متن راهنمای فرم مشاوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="عنوان")),
                ("value", models.PositiveIntegerField(default=0, verbose_name="عدد")),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="مثال: + یا سال",
                        max_length=20,
                        verbose_name="پسوند",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="check", max_length=40, verbose_name="آیکون"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "آمار",
                "verbose_name_plural": "آمار و دستاوردها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام موکل")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="عنوان / نوع پرونده"
                    ),
                ),
                ("content", models.TextField(verbose_name="متن نظر")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="testimonials/", verbose_name="تصویر"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="امتیاز (۱ تا ۵)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شود"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "نظر موکل",
                "verbose_name_plural": "نظرات موکلان",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="زمان مناسب تماس"
                    ),
                ),
                ("message", models.TextField(verbose_name="شرح مختصر موضوع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("in_progress", "در حال پیگیری"),
                            ("done", "انجام شد"),
                            ("archived", "بایگانی"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آی\u200cپی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="تاریخ ثبت",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="core.practicearea",
                        verbose_name="موضوع پرونده",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست مشاوره",
                "verbose_name_plural": "درخواست\u200cهای مشاوره",
                "ordering": ["-created_at"],
            },
        ),
    ]
