# Generated by Django 5.1.15 on 2026-09-18 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="نشانی اینترنتی",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی ویدیو",
                "verbose_name_plural": "دسته\u200cبندی ویدیوها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="تاریخ ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان ویدیو")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="نشانی اینترنتی",
                    ),
                ),
                (
                    "aparat_url",
                    models.CharField(
                        help_text="لینک کامل ویدیو (مثال: https://www.aparat.com/v/abc123) یا فقط کد ویدیو",
                        max_length=300,
                        verbose_name="لینک ویدیو در آپارات",
                    ),
                ),
                (
                    "aparat_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=60,
                        verbose_name="کد ویدیو",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="videos/", verbose_name="تصویر بندانگشتی"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="مثال: ۰۵:۳۲",
                        max_length=20,
                        verbose_name="مدت زمان",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه نخست"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شود"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد بازدید"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="videos.videocategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیو",
                "verbose_name_plural": "ویدیوها",
                "ordering": ["order", "-published_at"],
            },
        ),
    ]
